name: Android Build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api: [21, 30]
        options:
          - -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - id: avd-cache
        uses: actions/cache@v4
        with:
          path: ~/.android/avd/* ~/.android/adb*
          key: avd-${{matrix.api}}
      - name: enable kvm
        if: 0
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: create and cache avd
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{matrix.api}}
          force-avd-creation: false
          disable-animations: false
          arch: x86_64
          emulator-options: ${{matrix.options}}
          script: echo Generated AVD snapshot for caching
      - name: test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{matrix.api}}
          force-avd-creation: false
          disable-animations: false
          arch: x86_64
          emulator-options: -no-snapshot-save ${{matrix.options}}
          script: |
            cat /sys/kernel/debug/kvm/*/vcpu0/pid || :
            adb shell getprop
      - name: ls-R
        run: find -ls
